from pydantic import BaseModel, Field
from typing import List, Optional

class PatientLookupRequest(BaseModel):
    phone: str = Field(..., description="Patient registered phone number")
    access_code: str = Field(..., description="6-digit OTP code generated by the patient app")

class PatientLookupResponse(BaseModel):
    patientId: str
    name: str
    phone: str
    age: Optional[int] = None
    gender: Optional[str] = None
    blood_group: Optional[str] = None
    allergies: List[str] = []
    chronic_conditions: List[str] = []
    current_medications: List[str] = []
    past_surgeries: List[str] = []
    family_history: List[str] = []
    height: Optional[float] = None
    weight: Optional[float] = None
    bmi: Optional[float] = None
    bmi_category: Optional[str] = None
    active_consent_id: str
