version: '3.8'

services:
  patient-service:
    build:
      context: .
      dockerfile: patient_service/Dockerfile
    container_name: patient-service
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      - PORT=8001
    volumes:
      - ./patient_service:/app/patient_service
      - ./common_code:/app/common_code

  doctor-service:
    build:
      context: .
      dockerfile: doctor_service/Dockerfile
    container_name: doctor-service
    ports:
      - "8002:8002"
    env_file:
      - .env
    environment:
      - PORT=8002
    volumes:
      - ./doctor_service:/app/doctor_service
      - ./common_code:/app/common_code
